"""Fix indentation issue

Revision ID: 2bf367fb2ab7
Revises: cad612c923b8
Create Date: 2025-08-26 21:41:07.109207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf367fb2ab7'
down_revision = 'cad612c923b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('nano_material', sa.String(length=255), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    # ### end Alembic commands ###
