"""Add certificate system with additional fields

Revision ID: 435f408fc467
Revises: 2bf367fb2ab7
Create Date: 2025-08-27 19:51:38.682914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '435f408fc467'
down_revision = '2bf367fb2ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('certificate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cert_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nano_material', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('certificate_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificate_pkey')),
    sa.UniqueConstraint('cert_id', name=op.f('certificate_cert_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
